os: osx

addons:
  homebrew:
    packages:
      - pyenv
      - geckodriver
    casks:
      - firefox-beta
      - google-chrome-beta
      - chromedriver

before_install:
  - pyenv update && pyenv install pypy3.6-7.3.1

install: pip3 install -U pip3 setuptools nox

script: nox -s tests-pypy3
