dist: xenial
language: python
python: [ pypy3 ]

addons:
  chrome: stable
  firefox: latest

before_install:
  - bash ./github/scripts/chromedriver.sh
  - bash ./github/scripts/geckodriver.sh

install: pip install -U pip setuptools nox

script: nox -s tests-pypy3
