site_name: Scalpel
site_description: scalpel package documentation
site_author: Kevin Tewouda
site_url: https://scalpel.readthedocs.io

repo_name: lewoudar/scalpel
repo_url: https://github.com/lewoudar/scalpel/
edit_uri: tree/master/docs

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Static spider: static_spider.md
  - Selenium spider: selenium_spider.md
  - API: api.md


theme: material

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - mkautodoc
  - codehilite

extra_css:
  - css/custom.css