name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ,'windows-latest' ]
        python: [ 3.7, 3.8, 3.9 ]
        # windows and mac are slow to run python 3.9 so we skip these jobs
        # windows is also really slow on python 3.6 and sometimes produce weird errors so we skip it
        exclude:
          - os: windows-latest
            python: 3.9
          - os: windows-latest
            python: 3.6
          - os: macos-latest
            python: 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: python -m pip install -U pip nox
      - name: Lint
        run: nox -s lint
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.9'
      - name: Tests
        run: nox -s tests-${{ matrix.python }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.python == '3.9'
        with:
          files: ./coverage-core.xml,./coverage-any_io.xml,./coverage-green.xml
