name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        # probably need to port pypy usage on travis (more appropriate)
        # python: [pypy3, 3.6, 3.7, 3.8]
        python: [ 3.6, 3.7, 3.8, 3.9 ]
    #        exclude:
    #          - os: windows-latest
    #            python: pypy3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          pip install nox
      - name: Lint
        run: nox -s lint
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.9'
      - name: Tests
        run: nox -s tests-${{ matrix.python }}
        env:
          CODECOV_TOKEN: ${{ secrets.codecov_token }}
#      - name: Build and deploy
#        run: nox -s deploy
#        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
#        env:
#          POETRY_PYPI_TOKEN_PYPI: do_not_forget_it