name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ,'windows-latest' ]
        python: [ 3.6, 3.7, 3.8, 3.9 ]
        # windows and mac are slow to run python 3.9 so we skip these jobs
        exclude:
          - os: windows-latest
            python: 3.9
          - os: macos-latest
            python: 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: python -m pip install -U pip nox
      - name: Lint
        run: nox -s lint
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.9'
      - name: Tests
        run: nox -s tests-${{ matrix.python }}
        env:
          CODECOV_TOKEN: ${{ secrets.codecov_token }}
      - name: Build and deploy
        run: nox -s deploy
        if: >
          github.event_name == 'push' && contains(github.ref, 'refs/tags/') &&
          matrix.os == 'ubuntu-latest' && matrix.python == '3.9'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_token }}