name: PYPY_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python: [ pypy3 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install lxml utility libraries
        run: sudo apt install libxml2 && sudo snap install libxslt
      - name: Install python dependencies
        run: python -m pip install -U pip nox
      - name: Lint
        run: nox -s lint
      - name: Tests
        run: nox -s tests-${{ matrix.python }}
        env:
          CODECOV_TOKEN: ${{ secrets.codecov_token }}